name: painel-admin-temporario
static_sites:
  - name: painel-admin-temporario
    github:
      repo: DevsNexus2024/painel-admin-temporario
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    routes:
      - path: /
    catchall_document: index.html

